# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Unhedged
# Description of the Site
description: Explore the world with genuine idea and data
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Quantative, Prediction
# URL for the Image of custom Favicon
favicon-url: /assets/images/unhedged_symbol.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: contact@unhedged.kr
facebook_username:
twitter_username:
instagram_username:
linkedin_username:
github_username:
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Unhedged
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: We are a quantitative trading company constantly seeking Alpha. Our mission is to identify Alpha based on quantitative research and scientific reasoning. All of our investment process is fully automated, from data feeding to trade execution. We believe that the best way to find alphas is to explore the untapped paths with top-notch developers and researchers.
who-we-are:
  research: We build systematic strategies by applying modern statistical techniques to sophisticated large datasets to discover investment opportunities in financial markets. The models, based on cutting-edge mathematical modeling and statistical methods are tested by our rigorous framework to identify their validity, robustness and orthogonality.
  database: Data plays a very fundamental part to ensure all the performances of quantitative trading, from the research to execution. Our obsession with data made us create a unique database system - which not only serves accurate data in prompt but gives a seamless environment for researchers to experiment and deploy.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
